<template>
<router-view 
:id="id" 
:user-url="userUrl"
:save-user-profile-url="saveUserProfileUrl"
:save-user-dni-url="saveUserDniUrl" 
:save-user-public-profile-url="saveUserPublicProfileUrl"
:team-url="teamUrl"
:save-team-url="saveTeamUrl"
:edit-team-url="editTeamUrl"
:send-invitation-url="sendInvitationUrl"
:team-users-url="teamUsersUrl"
:team-invitations-url="teamInvitationsUrl"
:save-agreement-url="saveAgreementUrl"
:project-url="projectUrl"
:save-project-url="saveProjectUrl"
:edit-project-url="editProjectUrl"
:save-letter-url="saveLetterUrl"
></router-view>
</template>

<script>
export default {
  props: [
    "id",
	"userUrl",
	"saveUserProfileUrl",
	"saveUserDniUrl",
	"saveUserPublicProfileUrl",
	"teamUrl",
	"saveTeamUrl",
  "editTeamUrl",
	"sendInvitationUrl",
  "teamUsersUrl",
  "teamInvitationsUrl",
	"saveAgreementUrl",
	"projectUrl",
	"saveProjectUrl",
  "editProjectUrl",
	"saveLetterUrl",
  ],
}
</script>